const KEY='kinzhal-v7';const oldKeys=['kinzhal-v6','kinzhal-v5','kinzhal-v4','kinzhal-v3'];
const td=()=>new Date().toISOString().slice(0,10);
const def={profile:{age:24,height:'173–174',work:'08:00–19:00',weight:'',goal:'',calTarget:'',onboarded:false},daily:{},weights:[],workouts:[],meals:{},sets:{},extraExercises:{},activities:{},photos:[],chat:[]};
let raw=localStorage.getItem(KEY);if(!raw)for(const k of oldKeys){raw=localStorage.getItem(k);if(raw)break}
let S=raw?JSON.parse(raw):structuredClone(def);for(const k of Object.keys(def))if(S[k]===undefined)S[k]=structuredClone(def[k]);S.profile={...def.profile,...S.profile};S.photos=S.photos||[];
const tasks=['Утренняя вода','Размяться перед работой','Двигаться каждые 1–2 часа','Записать питание','Тренировка / активность','Записать сон'];
const plans={0:{name:'Восстановление',ex:[['Ходьба / бег на месте','10–15 мин',1],['Лёгкая разминка','5–8 мин',1]]},1:{name:'Грудь + корпус',ex:[['Отжимания','8–15 повторов',3],['Пресс','15–25 повторов',3],['Планка','30–45 сек',3],['Бег на месте','8–10 мин',1]]},2:{name:'Кардио + пресс',ex:[['Берпи','6–12 повторов',4],['Пресс','15–25 повторов',3],['Бег на месте','12–15 мин',1]]},3:{name:'Лёгкий день',ex:[['Отжимания','6–12 повторов',3],['Пресс','12–20 повторов',3],['Бег на месте','10 мин',1]]},4:{name:'Всё тело',ex:[['Отжимания','8–15 повторов',4],['Берпи','6–10 повторов',3],['Пресс','15–25 повторов',3],['Бег на месте','10–12 мин',1]]},5:{name:'Кардио',ex:[['Берпи','6–10 повторов',3],['Бег на месте','15–20 мин',1],['Пресс','15–20 повторов',3]]},6:{name:'Контрольная',ex:[['Отжимания','8–15 повторов',3],['Пресс','15–25 повторов',3],['Берпи','6–10 повторов',3],['Бег на месте','10 мин',1]]}};
function D(date=td()){return S.daily[date]||(S.daily[date]={water:0,sleep:'',cal:0,tasks:{},workout:false})}
function save(noRender=false){localStorage.setItem(KEY,JSON.stringify(S));if(!noRender)render()}
function plan(){return plans[new Date().getDay()]} function extras(){return S.extraExercises[td()]||(S.extraExercises[td()]=[])} function acts(){return S.activities[td()]||(S.activities[td()]=[])}
function head(){return `<div class="top"><div><div class="brand">Кинжал</div><div class="date">${new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</div></div><div class="avatar">🗡️</div></div>`}
function pct(){let d=D(),n=tasks.filter((_,i)=>d.tasks[i]).length;return Math.round(n/tasks.length*100)}
function kcalMin(met){let w=Number(S.profile.weight);return w?met*3.5*w/200:0}
function balance(){let d=D(),t=Number(S.profile.calTarget),w=Number(S.profile.weight);if(!t)return `<div class="notice">Дневная цель калорий пока не задана.</div>`;let x=d.cal-t;if(x<=0)return `<div class="balance good"><b>${Math.abs(x)} ккал до цели</b><span>Дополнительная активность из-за еды не требуется.</span></div>`;if(!w)return `<div class="balance warn"><b>+${x} ккал сверх цели</b><span>Внеси актуальный вес для ориентировочного расчёта активности.</span></div>`;let r=Math.ceil(x/kcalMin(8)),walk=Math.ceil(x/kcalMin(4.8));return `<div class="balance warn"><b>+${x} ккал сверх цели</b><span>Ориентир: около ${r} мин бега или ${walk} мин быстрой ходьбы. Это необязательная подсказка, а не «долг».</span><button class="secondary" id="suggestRun" data-min="${r}">+ Добавить ${r} мин бега</button></div>`}
function todayPage(){let d=D(),p=pct(),pl=plan();return `<section id="today" class="screen active">${head()}<div class="hero"><div class="heroRow"><div><div class="muted">Сегодня</div><div class="big">${p}%</div></div><b>${tasks.filter((_,i)=>d.tasks[i]).length}/${tasks.length} задач</b></div><div class="bar"><i style="width:${p}%"></i></div></div><div class="grid"><div class="stat"><span class="muted">Вода</span><b>${(d.water/1000).toFixed(2)} л</b></div><div class="stat"><span class="muted">Калории</span><b>${d.cal}</b></div><div class="stat"><span class="muted">Сон</span><b>${d.sleep||'—'} ч</b></div><div class="stat"><span class="muted">Вес</span><b>${S.profile.weight?S.profile.weight+' кг':'—'}</b></div></div><div class="sectionTitle">Тренировка дня</div><div class="card"><b>${pl.name}</b><div class="muted">${pl.ex.length} упражнения</div><button class="primary wide goto" style="margin-top:12px">Открыть тренировку</button></div><div class="sectionTitle">Вода</div><div class="chips"><button class="chip" data-water="250">+250 мл</button><button class="chip" data-water="500">+500 мл</button><button class="chip" data-water="-250">−250 мл</button></div><div class="sectionTitle">Задачи</div><div class="card">${tasks.map((t,i)=>`<label class="task"><span><input type="checkbox" data-task="${i}" ${d.tasks[i]?'checked':''}> ${t}</span></label>`).join('')}</div><div class="sectionTitle">Распорядок</div><div class="card"><div class="task"><b>07:00–08:00</b><span>Подъём, вода, завтрак</span></div><div class="task"><b>08:00–19:00</b><span>Работа + перерывы на движение</span></div><div class="task"><b>После работы</b><span>Тренировка / бег / прогулка</span></div><div class="task"><b>Перед сном</b><span>Записать итоги дня</span></div></div></section>`}
function trainingPage(){let pl=plan(),done=S.sets[td()]||{};return `<section id="training" class="screen">${head()}<div class="hero"><div class="muted">Тренировка сегодня</div><div class="big">${pl.name}</div></div><div class="sectionTitle">Упражнения</div><div class="card">${pl.ex.map((e,i)=>`<div class="exercise"><div class="row"><div><b>${e[0]}</b><div class="muted">${e[1]}</div></div><span>${e[2]} этап.</span></div><div class="sets">${Array.from({length:e[2]},(_,j)=>`<button class="set ${done[i+'-'+j]?'done':''}" data-set="${i}-${j}">${done[i+'-'+j]?'✓':j+1}</button>`).join('')}</div></div>`).join('')}${extras().map((e,i)=>`<div class="exercise"><div class="row"><div><b>${e.name}</b><div class="muted">${e.value} ${e.unit}</div></div><div><button class="danger" data-edit="${i}">✎</button> <button class="danger" data-del="${i}">×</button></div></div><label class="task"><span><input type="checkbox" data-xdone="${i}" ${e.done?'checked':''}> Выполнено</span></label></div>`).join('')}<button id="finish" class="primary wide">${D().workout?'Тренировка выполнена ✓':'Завершить тренировку'}</button></div><div class="sectionTitle">Добавить упражнение</div><form id="extraForm" class="card"><label>Название<input name="name" required placeholder="Бег на улице"></label><div class="form2"><label>Количество / время<input name="value" type="number" min="1" required></label><label>Единица<select name="unit"><option>мин</option><option>повторов</option><option>подходов</option><option>км</option></select></label></div><button class="secondary wide">+ Добавить</button></form><div class="sectionTitle">Дополнительная активность</div><form id="actForm" class="card"><label>Вид<select name="type"><option>Бег на улице</option><option>Бег на месте</option><option>Быстрая ходьба</option><option>Прогулка</option><option>Другое</option></select></label><label>Минуты<input name="minutes" type="number" min="1" max="600" required></label><button class="primary wide">Записать</button>${acts().map((a,i)=>`<div class="weightItem"><span>${a.type} • ${a.minutes} мин</span><span>${a.kcal?'≈ '+a.kcal+' ккал':''} <button class="danger" data-delact="${i}">×</button></span></div>`).join('')}</form><div class="sectionTitle">Таймер отдыха</div><div class="card"><div class="timer" id="timer">01:00</div><div class="chips"><button class="secondary" data-time="30">30 сек</button><button class="secondary" data-time="60">60 сек</button><button class="secondary" data-time="90">90 сек</button><button class="primary" id="timerStart">Старт</button></div></div></section>`}
function foodPage(){let m=S.meals[td()]||[];return `<section id="food" class="screen">${head()}<div class="hero"><div class="muted">Сегодня съедено</div><div class="big">${D().cal}${S.profile.calTarget?' / '+S.profile.calTarget:''} ккал</div>${balance()}</div><div class="sectionTitle">Добавить еду</div><form id="mealForm" class="card"><label>Что ел<input name="name" required placeholder="Например: бургер"></label><label>Калории<input name="cal" type="number" min="0" max="5000" required></label><button class="primary wide">Добавить</button></form><div class="sectionTitle">Дневник</div><div class="card">${m.length?m.map((x,i)=>`<div class="meal"><span>${x.name}</span><span>${x.cal} ккал <button class="danger" data-delmeal="${i}">×</button></span></div>`).join(''):'<span class="muted">Пока пусто.</span>'}</div></section>`}
function weekStats(){let now=new Date(),days=[];for(let i=6;i>=0;i--){let d=new Date(now);d.setDate(now.getDate()-i);days.push(d.toISOString().slice(0,10))}let wo=days.filter(x=>S.workouts.includes(x)).length,water=days.reduce((a,x)=>a+(S.daily[x]?.water||0),0),cal=days.reduce((a,x)=>a+(S.daily[x]?.cal||0),0);return {wo,water:Math.round(water/100)/10,cal}}
function progressPage(){let st=weekStats();return `<section id="progress" class="screen">${head()}<div class="kpis"><div class="kpi"><b>${st.wo}</b><span class="muted">тренировок / 7 дн.</span></div><div class="kpi"><b>${st.water} л</b><span class="muted">воды / 7 дн.</span></div><div class="kpi"><b>${st.cal}</b><span class="muted">ккал записано</span></div></div><div class="sectionTitle">Вес</div><form id="weightForm" class="card"><label>Вес сегодня, кг<input name="weight" type="number" min="30" max="300" step="0.1" required></label><button class="primary wide">Сохранить вес</button><canvas id="weightChart" width="640" height="190"></canvas><div>${S.weights.slice(-8).reverse().map(x=>`<div class="weightItem"><span>${x.date}</span><b>${x.value} кг</b></div>`).join('')}</div></form><div class="sectionTitle">Фото прогресса</div><div class="card"><input id="photoInput" class="photoInput" type="file" accept="image/*"><button id="photoBtn" class="primary wide">📸 Добавить фото</button><div class="notice">Фото сохраняются только на этом устройстве в приложении.</div><div class="photoGrid">${S.photos.map((p,i)=>`<div class="photo"><img src="${p.data}" alt="Фото прогресса ${p.date}"><button data-delphoto="${i}">×</button></div>`).join('')}</div></div></section>`}
function remaining(){let t=Number(S.profile.calTarget),c=Number(D().cal||0);return t?t-c:null}
function mealIdeas(kind='meal'){let r=remaining(),base=kind==='snack'?[['Греческий йогурт + ягоды','≈150–250 ккал'],['Творог + фрукт','≈200–300 ккал'],['Яблоко + небольшая порция орехов','≈180–250 ккал']]:[['Курица/индейка + рис или гречка + овощи','≈450–650 ккал'],['Омлет из яиц + овощи + цельнозерновой хлеб','≈350–550 ккал'],['Рыба + картофель/крупа + салат','≈450–650 ккал']];if(r!==null&&r<350)base=kind==='snack'?[['Йогурт без большого количества добавленного сахара','≈100–180 ккал'],['Фрукт','≈70–130 ккал'],['Творог небольшой порцией','≈120–220 ккал']]:[['Омлет + овощи','≈250–350 ккал'],['Творог + овощи/зелень','≈250–350 ккал'],['Лёгкий суп + салат','≈250–400 ккал']];return base}
function aiReply(q){let t=q.toLowerCase(),d=D(),r=remaining(),sleep=Number(d.sleep),water=d.water/1000,pl=plan(),prefix='';if(r!==null)prefix=`Сегодня записано ${d.cal} из ${S.profile.calTarget} ккал (${r>=0?'осталось около '+r:'выше цели примерно на '+Math.abs(r)} ккал). `;else prefix=`Сегодня записано ${d.cal} ккал. Дневная цель пока не задана. `;
if(/ужин|поесть|есть сейчас|голод|перекус|еда|кушать/.test(t)){let snack=/перекус/.test(t),ideas=mealIdeas(snack);return prefix+`Варианты ${snack?'перекуса':'приёма пищи'}: `+ideas.map(x=>`${x[0]} (${x[1]})`).join('; ')+`. Ориентируйся на голод и размер порции; конкретное время еды не обязано быть фиксированным.`}
if(/слад|пицц|бургер|фаст|можно/.test(t)){return prefix+`Можно включать и более калорийные продукты — важнее общий рацион и порция. Если хочется именно этого, возьми разумную порцию, добавь белок/овощи и просто запиши калории. Не нужно «наказывать» себя тренировкой за еду.`}
if(/до трен|перед трен/.test(t)){return `Перед тренировкой обычно удобно поесть за 1–3 часа: углеводы + немного белка, без слишком тяжёлой порции. Например: банан и йогурт, овсянка с йогуртом, рис/гречка с курицей. Если тренировка скоро и ты не голоден — специально есть не обязательно.`}
if(/после трен/.test(t)){return `После тренировки сделай обычный приём пищи с белком и углеводами: например курица/рыба/яйца/творог плюс крупа или картофель и овощи. Специальное «окно» в несколько минут ловить не нужно.`}
if(/трен|бег|спорт|заним/.test(t)){let msg=`Сегодня по плану: «${pl.name}». `;if(sleep&&sleep<6)msg+=`Ты записал ${sleep} ч сна — я бы сегодня снизил интенсивность: меньше берпи, спокойный бег/ходьба и не работать до отказа. `;else msg+=`Если самочувствие обычное, можешь выполнять план и регулировать темп по ощущениям. `;return msg+`Если появляется боль, головокружение или необычная одышка — тренировку лучше прекратить.`}
if(/вод|пить/.test(t)){return `Сегодня записано ${(water).toFixed(2)} л воды. Пей в течение дня по жажде и больше при жаре/активном потоотделении; не нужно пытаться выпить большой объём сразу ради цифры.`}
if(/сон|спал|высп/.test(t)){return sleep?`Сегодня у тебя записано ${sleep} ч сна. ${sleep<7?'Это ниже обычного ориентира для взрослого, поэтому сегодня разумно сделать нагрузку легче и постараться дать себе больше времени на сон следующей ночью.':'По записи сна явного повода уменьшать обычную тренировку нет — ориентируйся ещё и на самочувствие.'}`:`Сон сегодня ещё не записан. Внеси его во вкладке «Ещё», и я смогу учитывать его в советах по тренировке.`}
if(/день|анализ|разбер|итог/.test(t)){let done=tasks.filter((_,i)=>d.tasks[i]).length;return `Разбор дня: ${done}/${tasks.length} задач, вода ${(water).toFixed(2)} л, питание ${d.cal}${S.profile.calTarget?' из '+S.profile.calTarget:''} ккал, сон ${d.sleep||'не записан'} ч, тренировка ${d.workout?'выполнена':'ещё не отмечена'}. ${r!==null&&r<0?'Калории сегодня выше цели, но компенсировать их наказательной тренировкой не нужно — просто продолжай обычный режим.':''}`}
if(/завтрак/.test(t))return `Для завтрака подойдут варианты с белком и клетчаткой: яйца + овощи + хлеб; овсянка + йогурт/творог + ягоды; творог + фрукт. Выбирай то, что удобно и помогает не быть голодным через час.`;
return `Я пока бесплатный локальный помощник и лучше всего понимаю вопросы про питание, воду, сон и тренировки. Попробуй: «Что мне поесть сейчас?», «Разбери мой день», «Что перед тренировкой?» или «Я плохо спал — как тренироваться?».`}
function assistantPage(){let chat=S.chat||[];return `<section id="assistant" class="screen">${head()}<div class="hero"><div class="muted">Бесплатный локальный помощник</div><div class="big" style="font-size:27px">Кинжал AI 💬</div><div class="notice">Работает без сервера и оплаты. Советы формируются по данным, которые ты внёс в приложение.</div></div><div class="sectionTitle">Быстрый вопрос</div><div class="chips"><button class="chip askquick" data-q="Что мне поесть сейчас?">🍽 Что поесть</button><button class="chip askquick" data-q="Разбери мой день">📊 Разбор дня</button><button class="chip askquick" data-q="Что перед тренировкой?">🏋️ Перед тренировкой</button><button class="chip askquick" data-q="Стоит сегодня тренироваться?">⚡ Тренировка</button></div><div class="sectionTitle">Чат</div><div class="card chatbox">${chat.length?chat.slice(-20).map(m=>`<div class="bubble ${m.role}"><b>${m.role==='user'?'Ты':'Кинжал'}</b><div>${esc(m.text)}</div></div>`).join(''):'<div class="bubble bot"><b>Кинжал</b><div>Привет. Я вижу только данные, которые ты сам внёс в приложение. Спроси, что лучше поесть, как провести тренировку или попроси разобрать сегодняшний день.</div></div>'}</div><form id="chatForm" class="chatinput"><input name="q" autocomplete="off" placeholder="Напиши вопрос…" required><button class="primary">➤</button></form><button id="clearChat" class="secondary wide" style="margin-top:10px">Очистить историю чата</button><div class="notice">Это общие рекомендации по образу жизни, а не медицинская консультация.</div></section>`}
function esc(x){return String(x).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function ask(q){S.chat=S.chat||[];S.chat.push({role:'user',text:q},{role:'bot',text:aiReply(q)});if(S.chat.length>40)S.chat=S.chat.slice(-40);save();show('assistant');setTimeout(()=>scrollTo(0,document.body.scrollHeight),30)}
function morePage(){return `<section id="more" class="screen">${head()}<div class="sectionTitle">Профиль и цели</div><form id="profileForm" class="card"><label>Возраст<input value="${S.profile.age}" disabled></label><label>Рост<input value="${S.profile.height}" disabled></label><label>Текущий вес, кг<input name="weight" type="number" step="0.1" value="${S.profile.weight}"></label><label>Желаемый вес, кг<input name="goal" type="number" step="0.1" value="${S.profile.goal}"></label><label>Дневная цель калорий<input name="calTarget" type="number" min="1000" max="6000" value="${S.profile.calTarget}"></label><label>Сон прошлой ночью, часов<input name="sleep" type="number" min="0" max="24" step="0.5" value="${D().sleep}"></label><button class="primary wide">Сохранить</button></form><div class="sectionTitle">Данные</div><div class="card"><button id="export" class="secondary wide">Скачать резервную копию</button><label class="secondary wide" style="text-align:center;margin-top:9px">Восстановить из копии<input id="import" type="file" accept="application/json" class="photoInput"></label><button id="reset" class="dangerbtn wide" style="margin-top:9px">Очистить все данные</button></div><div class="notice">Кинжал v7 • данные хранятся локально на устройстве.</div></section>`}
function nav(){return `<nav class="nav"><div class="navin">${[['today','⌂','Сегодня'],['training','💪','Тренировки'],['food','🍽','Питание'],['assistant','💬','Помощник'],['progress','📈','Прогресс'],['more','☰','Ещё']].map(x=>`<button data-page="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div></nav>`}
let active='today',timerSec=60,timerId;
function render(){document.getElementById('app').innerHTML=`<main class="app">${todayPage()}${trainingPage()}${foodPage()}${assistantPage()}${progressPage()}${morePage()}</main>${nav()}${!S.profile.onboarded?onboarding():''}`;show(active);bind();drawChart()}
function show(id){active=id;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0)}
function onboarding(){return `<div class="modal"><form id="onboard" class="modalbox"><div class="brand">Добро пожаловать в «Кинжал» 🗡️</div><p class="muted">Настроим основу. Вес можно оставить пустым до взвешивания.</p><label>Текущий вес, кг<input name="weight" type="number" step="0.1"></label><label>Желаемый вес, кг<input name="goal" type="number" step="0.1"></label><label>Дневная цель калорий<input name="calTarget" type="number" min="1000" max="6000"></label><button class="primary wide">Начать</button><button type="button" id="skipOnboard" class="secondary wide" style="margin-top:8px">Заполнить позже</button></form></div>`}
function bind(){
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('.goto').forEach(b=>b.onclick=()=>show('training'));
document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{D().water=Math.max(0,D().water+Number(b.dataset.water));save()});document.querySelectorAll('[data-task]').forEach(c=>c.onchange=()=>{D().tasks[c.dataset.task]=c.checked;save()});
document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{let z=S.sets[td()]||(S.sets[td()]={});z[b.dataset.set]=!z[b.dataset.set];save()});
let ef=document.getElementById('extraForm');if(ef)ef.onsubmit=e=>{e.preventDefault();let f=new FormData(ef);extras().push({name:f.get('name'),value:Number(f.get('value')),unit:f.get('unit'),done:false});save();show('training')};
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let e=extras()[+b.dataset.edit],n=prompt('Название упражнения:',e.name);if(n===null)return;let v=prompt('Количество / время:',e.value);if(v===null)return;e.name=n.trim()||e.name;e.value=Math.max(1,Number(v)||e.value);save();show('training')});
document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{extras().splice(+b.dataset.del,1);save();show('training')});document.querySelectorAll('[data-xdone]').forEach(c=>c.onchange=()=>{extras()[+c.dataset.xdone].done=c.checked;save();show('training')});
let af=document.getElementById('actForm');if(af)af.onsubmit=e=>{e.preventDefault();let f=new FormData(af),type=f.get('type'),minutes=+f.get('minutes'),met=String(type).includes('Бег')?8:type==='Быстрая ходьба'?4.8:type==='Прогулка'?3.3:0;acts().push({type,minutes,kcal:kcalMin(met)?Math.round(kcalMin(met)*minutes):0});save();show('training')};document.querySelectorAll('[data-delact]').forEach(b=>b.onclick=()=>{acts().splice(+b.dataset.delact,1);save();show('training')});
let sr=document.getElementById('suggestRun');if(sr)sr.onclick=()=>{let m=+sr.dataset.min;acts().push({type:'Бег на месте',minutes:m,kcal:Math.round(kcalMin(8)*m)});save();show('training')};
let f=document.getElementById('finish');if(f)f.onclick=()=>{D().workout=true;D().tasks[4]=true;if(!S.workouts.includes(td()))S.workouts.push(td());save();show('training')};
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{timerSec=+b.dataset.time;drawTimer()});let ts=document.getElementById('timerStart');if(ts)ts.onclick=()=>{clearInterval(timerId);timerId=setInterval(()=>{if(timerSec<=0){clearInterval(timerId);return}timerSec--;drawTimer()},1000)};
let mf=document.getElementById('mealForm');if(mf)mf.onsubmit=e=>{e.preventDefault();let q=new FormData(mf);(S.meals[td()]||(S.meals[td()]=[])).push({name:q.get('name'),cal:+q.get('cal')});D().cal=S.meals[td()].reduce((a,b)=>a+b.cal,0);save();show('food')};document.querySelectorAll('[data-delmeal]').forEach(b=>b.onclick=()=>{S.meals[td()].splice(+b.dataset.delmeal,1);D().cal=S.meals[td()].reduce((a,b)=>a+b.cal,0);save();show('food')});
let wf=document.getElementById('weightForm');if(wf)wf.onsubmit=e=>{e.preventDefault();let v=+new FormData(wf).get('weight');S.profile.weight=v;S.weights=S.weights.filter(x=>x.date!==td());S.weights.push({date:td(),value:v});save();show('progress')};
let pf=document.getElementById('profileForm');if(pf)pf.onsubmit=e=>{e.preventDefault();let q=new FormData(pf);S.profile.weight=q.get('weight');S.profile.goal=q.get('goal');S.profile.calTarget=q.get('calTarget');D().sleep=q.get('sleep');save();show('more')};
let pb=document.getElementById('photoBtn'),pi=document.getElementById('photoInput');if(pb)pb.onclick=()=>pi.click();if(pi)pi.onchange=()=>{let file=pi.files[0];if(!file)return;if(file.size>4*1024*1024){alert('Выбери фото до 4 МБ.');return}let r=new FileReader();r.onload=()=>{S.photos.unshift({date:td(),data:r.result});if(S.photos.length>12)S.photos.length=12;try{save();show('progress')}catch{S.photos.shift();alert('На устройстве не хватило локального места для фото.')}};r.readAsDataURL(file)};document.querySelectorAll('[data-delphoto]').forEach(b=>b.onclick=()=>{S.photos.splice(+b.dataset.delphoto,1);save();show('progress')});
let ex=document.getElementById('export');if(ex)ex.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='kinzhal-backup-'+td()+'.json';a.click()};let im=document.getElementById('import');if(im)im.onchange=()=>{let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.profile||!x.daily)throw 0;S=x;S.profile={...def.profile,...S.profile};save();alert('Резервная копия восстановлена.')}catch{alert('Не удалось прочитать резервную копию.')}};r.readAsText(im.files[0])};let rb=document.getElementById('reset');if(rb)rb.onclick=()=>{if(confirm('Удалить все данные Кинжала?')){localStorage.clear();location.reload()}};
let ob=document.getElementById('onboard');if(ob)ob.onsubmit=e=>{e.preventDefault();let q=new FormData(ob);S.profile.weight=q.get('weight');S.profile.goal=q.get('goal');S.profile.calTarget=q.get('calTarget');S.profile.onboarded=true;save()};let sk=document.getElementById('skipOnboard');if(sk)sk.onclick=()=>{S.profile.onboarded=true;save()};
let cf=document.getElementById('chatForm');if(cf)cf.onsubmit=e=>{e.preventDefault();let q=new FormData(cf).get('q').trim();if(q)ask(q)};document.querySelectorAll('.askquick').forEach(b=>b.onclick=()=>ask(b.dataset.q));let cc=document.getElementById('clearChat');if(cc)cc.onclick=()=>{S.chat=[];save();show('assistant')};
}
function drawTimer(){let e=document.getElementById('timer');if(e)e.textContent=String(Math.floor(timerSec/60)).padStart(2,'0')+':'+String(timerSec%60).padStart(2,'0')}
function drawChart(){let c=document.getElementById('weightChart');if(!c)return;let a=S.weights.slice(-12);let x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#273244';x.lineWidth=1;for(let i=1;i<4;i++){x.beginPath();x.moveTo(30,i*h/4);x.lineTo(w-15,i*h/4);x.stroke()}if(a.length<2){x.fillStyle='#9ba7b8';x.font='16px system-ui';x.fillText('Добавь минимум 2 записи веса для графика',35,95);return}let vals=a.map(z=>+z.value),min=Math.min(...vals)-1,max=Math.max(...vals)+1;x.strokeStyle='#e11d48';x.lineWidth=4;x.beginPath();a.forEach((z,i)=>{let px=30+i*(w-55)/(a.length-1),py=15+(max-z.value)*(h-35)/(max-min);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#f7f8fa';a.forEach((z,i)=>{let px=30+i*(w-55)/(a.length-1),py=15+(max-z.value)*(h-35)/(max-min);x.beginPath();x.arc(px,py,5,0,Math.PI*2);x.fill()})}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});